### ISSUE TITLE
붙여넣기 시 행 추가

### ISSUE THREAD

**Issue by flyskyko** [nhnent/fe.application-grid#1]
엑셀에서 데이터를 복사하여 붙여넣기할 때 만약 붙여넣을 행이 제일 마지막 행이고 복사한 데이터가 두 개 이상의 행을 가지고 있을 때  그리드에서 자동으로 행이 늘어나는 기능이 제공되나요?
제가 예제 페이지를 통해 테스트했을 때는 행이 늘어나지 않고 제일 마지막 행만 복사한 데이터의 첫번째 행으로 변경되어서 문의드립니다.

**Comment by dongwoo-kim** [comment]
먼저, 첫번째 이슈등록 감사드립니다!! :)
문의주신 기능은 현재 제공되지 않고 있습니다. 직접 테스트에서 확인하신 내용과 동일하게 동작하고 있구요, 필요하시다면 내부 검토 후에 9월 배포 목록에 추가될 수 있을 것 같습니다.

**Comment by flyskyko** [comment]
감사합니다. 검토 후에 반영되길 바랍니다. ^^

**Comment by dongwoo-kim** [comment]
1.0.4 버전에 반영되었습니다.

**Comment by icebelle** [comment]
Works Mobile - https://www.worksmobile.com
--------------------------------------------
류진경(icebelle@nhnent.com) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [fe.application-grid] 붙여넣기 시 행 추가 (#1)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
류진경(icebelle@nhnent.com) 님이 남기신 메시지 입니다.
--------------------------------------------
[부재기간 : 2015-09-30 09:30 ~ 2015-10-02 18:30 GMT +09:00]<br>개인 휴가(수~금)로 부재입니다.<br>메일주시면 확인하는대로 회신 드리겠습니다.<br>급한 용무는 휴대폰으로 연락 부탁드립니다.
--------------------------------------------

**Comment by flyskyko** [comment]
:+1:
