### ISSUE TITLE
그리드 셀 클릭시, 클릭이 안되게 하고 싶습니다.

### ISSUE THREAD

**Issue by KHI6304** [nhnent/fe.application-grid#1455]
![image](https://user-images.githubusercontent.com/16223964/131094766-1e9af1fd-faf6-42bd-8611-c541358f67bc.png)

셀 클릭시 셀의 테두리 색이 변환안되게 하고 싶은데

혹시 방법이 있을 지 궁금하여 글 남깁니다.

**Comment by jonghwajoa** [comment]
applyTheme설정을 이용하면 될것같네요.   

```js
TuiGrid.applyTheme('striped', {
  cell: {
    focused: {
      border: '0',
    },
  },
});
```
