### ISSUE TITLE
setColumns 사용 시의 date-picker 활용 이슈 문의

### ISSUE THREAD

**Issue by yo100** [nhnent/fe.application-grid#185]
안녕하세요. tui grid 사용 중 문의사항이 생겨 글 남깁니다.

현재 그리드 생성시 createGrid라는 별도의 모듈성 펑션(자체 제작)을 활용하여 
new tui.Grid 후 , setColumns 메소드를 활용해 컬럼 속성 값들을 지정하고 있습니다.

 
    $.fn.createGrid = function(){

	var grid = new tui.Grid({
	    el: $(this) 
	    ,columnOptions : {resizable:true}
	    //,virtualScrolling: true
	    ,displayRowCount: 10
	    ,bodyHeight : 'fitToParent'
	    //,bodyWidth : 200
	    ,useClientSort:true
		,minRowHeight : 20
		,maxRowHeight : 50
        ,header: {height : 30}
        ,rowHeaders: ['checkbox'] 
        ,minimumColumnWidth: 50
	    ,scrollx : true
	    ,scrolly : false
	    ,editingEvent: 'dblclick'
	    ,selectionUnit: 'row'
	    ,heightResizable : true 
	    
	});
	
	return grid;
    }
    var grid1 = $('#grid1').createGrid();
	var columns = [
		{
	            title: 'DatePicker(기본)',
	            name: 'c2',
	            editOptions: {
	                type: 'text',
	                useViewMode: false
	            },
	            component: {
	                name: 'datePicker'
	            }
	        }
			
	];
	
	grid1.setColumns(columns);

위와 같은 방식으로 date picker 생성시 지정 컬럼에 date picker 활성화가 되지 않고 있습니다.
답변 부탁드리겠습니다. 감사합니다.

**Comment by seonim-ryu** [comment]
@yo100 
`setColumns` API의 경우 이미 설정된 컬럼 모델 값을 변경하기 위한 용도입니다.
위에 사용하신 예제를 보았을 때 그리드 생성 시에 `columns` 옵션이 설정되지 않아서 동작을 안한 것으로 보이네요.
다음과 같이 변경하여 사용 바랍니다.
```js
$.fn.createGrid = function() {
  var grid = new tui.Grid({
    columns: [ ... ]
  });
});
```
