### ISSUE TITLE
grid 에서 cell 컨텐츠가 길어졌을 때 checkbox 높이 자동으로 조절 안됨 및 선택영역 위치 틀어짐 문제

### ISSUE THREAD

**Issue by nsphhee** [nhnent/fe.application-grid#2026]
![image](https://github.com/nhn/tui.grid/assets/157661515/17fca515-793f-4e5d-8171-ba217978247f)

tui gird 에서 table cell 영역 컨텐츠가 길어졌을 때 

1. checkbox 높이가 자동으로 적용되지 않음
2. 포커스 영역 위치 틀어짐

방법이 있을까요?

@version 4.21.22

**Comment by nsphhee** [comment]
rowHeight: 'auto' 

옵션으로 해결했습니다.

**Comment by bernice75** [comment]
혹시 단순히 auto 옵션을 추가로 설정한 것 만으로 해결하셨나요?
동일한 문제를 겪고 있는데 기존 부트스트랩 css/js와 충돌이 있는지 예제처럼 적용되지 않고 있습니다.

**Comment by nsphhee** [comment]
네 저 옵션 추가로 해결되었습니다. 

![image](https://github.com/nhn/tui.grid/assets/157661515/e516bd99-0a46-4023-9ab9-2befe8a870f3)

**Comment by bernice75** [comment]
감사합니다!!!
