### ISSUE TITLE
Column Sorting: Get Sort Information Without Actual Sorting and DataSource

### ISSUE THREAD

**Issue by lsy7851** [nhnent/fe.application-grid#2057]
**Summary**

When sorting columns, is it possible to receive only the sorting information using methods like getSortState instead of actually sorting the data?
We would like to fetch new data from the server when the sort button is clicked, rather than sorting the already retrieved data.

**Version**

4.21.4

**Additional context**

The dataSource feature cannot be used due to the issues of multi-column sorting and the mismatch between the types required by the dataSource feature and the types of the actual retrieved data.

---

**Summary**

컬럼 정렬 시 실제로 정렬 되는 대신 getSortState 메소드 등을 이용해 정렬 정보만 받을 수 있나요?
정렬 버튼을 누를 경우 조회 된 데이터 중 정렬 하는 것이 아닌 서버에서 새로 데이터를 조회하려고 합니다.

**Version**

4.21.4

**Additional context**

dataSource 기능은 멀티 컬럼 정렬, dataSource 기능이 요구하는 타입과 실제 조회되는 데이터의 타입이 불일치 하는 문제로 사용 할 수 없는 상황입니다.

**Comment by HIMZ5221** [comment]
```javascript

grid.on('beforeSort', (ev) => {
        ev.stop()
        console.log(ev)
    });

```

beforeSort 이벤트로 구현하시는 건 어떨까요?
