### ISSUE TITLE
When appendRow(..., { focus: true }) is performed after filtering, an error occurs: "Cannot read properties of undefined (reading 'rowKey')"

### ISSUE THREAD

**Issue by xman2310** [nhnent/fe.application-grid#2071]
**Describe the bug**
When appendRow(..., { focus: true }) is performed after filtering, an error occurs: "Cannot read properties of undefined (reading 'rowKey')"

**To Reproduce**
Source URL : https://codesandbox.io/p/sandbox/dank-architecture-mr4hr7?file=%2Fsrc%2FApp.js%3A15%2C1

https://github.com/user-attachments/assets/54c0583d-f380-4c42-ba3e-b9f840ee0ff5

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 129.0.6668.90(64bit)

**Comment by HIMZ5221** [comment]
![clipboardImage_24_1010_093648_876](https://github.com/user-attachments/assets/20882928-85ae-4da0-8b49-cebd17301503)

**Comment by HIMZ5221** [comment]
![Uploading 스크린샷 2024-10-10 132036.png…]()

**Comment by HIMZ5221** [comment]
![2024-10-10 132036](https://github.com/user-attachments/assets/8ef58e02-99de-4f23-841f-9b8d50809646)

**Comment by xman2310** [comment]
If you add one line **after filtering** is applied, the problem occurs.

After filtering is applied...
